from django.utils.translation import gettext_lazy as _

DATA_STATUS_DUPLICATED = "DUPLICATED"
DATA_STATUS_PENDING = "PENDING"
DATA_STATUS_DELETED = "DELETED"
DATA_STATUS_MOVED = "MOVED"
DATA_STATUS_PUBLIC = "PUBLIC"
DATA_STATUS_UNDEF = "UNDEF"
DATA_STATUS_NOT_AVAILABLE = "NOTAVAIL"

DATA_STATUS = (
    (DATA_STATUS_NOT_AVAILABLE, _("not available/not public")),
    (DATA_STATUS_DUPLICATED, _("duplicated")),
    (DATA_STATUS_PUBLIC, _("public")),
    (DATA_STATUS_PENDING, _("pending")),
    (DATA_STATUS_MOVED, _("moved")),
    (DATA_STATUS_DELETED, _("deleted")),
    (DATA_STATUS_UNDEF, _("undefined")),
)


EXPORTATION_STATUS_PENDING = "PENDING"
EXPORTATION_STATUS_DELETED = "DELETED"
EXPORTATION_STATUS_TODO = "TODO"
EXPORTATION_STATUS_DONE = "DONE"
EXPORTATION_STATUS_WIP = "WIP"

EXPORTATION_STATUS = (
    (EXPORTATION_STATUS_DONE, _("done")),
    (EXPORTATION_STATUS_PENDING, _("pending")),
    (EXPORTATION_STATUS_TODO, _("to do")),
    (EXPORTATION_STATUS_DELETED, _("deleted")),
    (EXPORTATION_STATUS_WIP, _("in progress")),
)
