# Generated by Django 4.1.7 on 2023-04-13 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pid_provider", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PidProviderBadRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "basename",
                    models.TextField(blank=True, null=True, verbose_name="Basename"),
                ),
                (
                    "finger_print",
                    models.CharField(blank=True, max_length=65, null=True),
                ),
                ("error_type", models.CharField(blank=True, max_length=65, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("xml", models.FileField(upload_to="bad_request")),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="pidproviderbadrequest",
            index=models.Index(
                fields=["basename"], name="pid_provide_basenam_8cb8ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pidproviderbadrequest",
            index=models.Index(
                fields=["finger_print"], name="pid_provide_finger__b3b19c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pidproviderbadrequest",
            index=models.Index(
                fields=["error_type"], name="pid_provide_error_t_b4eaa4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pidproviderbadrequest",
            index=models.Index(
                fields=["error_message"], name="pid_provide_error_m_ca5dbc_idx"
            ),
        ),
    ]
