# Generated by Django 4.1.7 on 2023-04-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pid_provider", "0002_pidproviderbadrequest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pidproviderbadrequest",
            name="error_type",
            field=models.TextField(blank=True, null=True),
        ),
    ]
