# Generated by Django 4.1.7 on 2023-04-14 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "article",
            "0003_rename_article_art_languag_5b1006_idx_article_art_languag_1293e9_idx_and_more",
        ),
        ("pid_provider", "0003_alter_pidproviderbadrequest_error_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="xmldocpid",
            name="article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="article.article",
            ),
        ),
    ]
